version: '3'
services:

  webserver:
    build:
      context: ./webserver
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - INSTALL_PDO_MYSQL=${INSTALL_PDO_MYSQL}
    image: php:7-apache
    container_name: lamp_stack__webserver
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ./webserver/php/php.ini:/usr/local/etc/php/conf.d/dev_stack.ini
      - ./webserver/apache/apache2.conf:/etc/apache2/conf-available/dev_stack.conf
      - ./webserver/apache/vhosts.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - ${HTTP_PORT}:80
    links:
      - mysql
      - phpmyadmin
      - mailcatcher
    environment:
      - TZ=${TIMEZONE}
      
  mysql:
    image: mysql:8
    container_name: lamp_stack__mysql
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/dev_stack.cnf
      - ./mysql/build.sql:/docker-entrypoint-initdb.d/build.sql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    build: ./phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: lamp_stack__phpmyadmin
    volumes:
      - ./phpmyadmin/config.php:/etc/phpmyadmin/config.user.inc.php
    links:
      - mysql
    environment:
      - TZ=${TIMEZONE}
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root

  mailcatcher:
    image: schickling/mailcatcher
    container_name: lamp_stack__mailcatcher